osc:
  ip: "192.168.1.202" # IP for visuals computer
  port: 1337

memcached:
  host: "127.0.0.1"
  port: 11211
  key: "badge_data"

polling_interval: 1  # Time in seconds between checks

mappings:
  - path: "/composition/layers/1/clips/1/connect"
    field: "player_connect"
    type: "launch"

  - path: "/total_score"
    field: "score"
    type: "number"

  - path: "/composition/layers/2/clips/1/video/source/blocktextgenerator/text/params/lines"
    field: "player_name"
    type: "text"

