osc:
  ip: "192.168.1.202"
  port: 1337

mappings:
  - path: "/composition/layers/4/clips/6/connect"
    field: "player_connect"
    type: "launch"

  - path: "/total_score"
    field: "score"
    type: "number"

  - path: "/composition/layers/4/clips/10/video/source/blocktextgenerator/text/params/lines"
    field: "player_name"
    type: "text"

