osc:
  ip: "192.168.1.202"
  port: 1337

mappings:
  - path: "/composition/layers/4/clips/6/connect"
    field: "launch_show"
    type: "launch"

  - path: "/composition/layers/1/clips/2/video/opacity"
    field: "opacity_value"
    type: "number"

  - path: "/composition/layers/3/clips/5/name"
    field: "clip_name"
    type: "text"

